cleanup(gh-actions/build-debian): Unify steps common tasks and make apt faster
canonical/desktop-engineering pull request #57
Opened 2024-12-18 18:49 UTC by 3v1n0

Simplify the action and move the common docker steps in a script that is shared by all the steps.

2025-01-22 22:51 UTC, 3v1n0 commented
@didrocks can you give this a look please? :)

2025-01-23 13:48 UTC, didrocks requested changes
I only have 3 small nitpicks, but should be good to go then!

2025-01-23 13:48 UTC, didrocks commented on gh-actions/common/build-debian/prepare-container.sh
> +  echo "$locales_needed" > "${locales_required_check}"
nitpick: missing `${locales_needed}`

2025-01-23 13:48 UTC, didrocks commented on gh-actions/common/build-debian/prepare-container.sh
> +  apt install dctrl-tools
didn’t we say we always use `-y`?

2025-01-23 13:48 UTC, didrocks commented on gh-actions/common/build-debian/prepare-container.sh
> +apt dist-upgrade
ditto on "yes" by default?

2025-01-23 16:29 UTC, 3v1n0 commented on gh-actions/common/build-debian/prepare-container.sh
> +  apt install dctrl-tools
Well yeah... I had avoided it through env variables though, but let me do it...

2025-01-23 16:32 UTC, 3v1n0 commented on gh-actions/common/build-debian/prepare-container.sh
> +  apt install dctrl-tools
Actually it would be pretty dumb, because exactly to avoid this to be forgotten I did initially:

`echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90aptyes`

2025-01-23 16:41 UTC, didrocks commented on gh-actions/common/build-debian/prepare-container.sh
> +  apt install dctrl-tools
You’re correct

2025-01-23 16:41 UTC, didrocks approved these changes
Good work!

2025-01-23 16:47 UTC, 3v1n0 commented
Cool, FYI I've dropped the last commit since it got upstreamed at https://github.com/canonical/setup-lxd/pull/25 :)

2025-01-23 18:20 UTC, merged