Allow action caller to specify a working directory
canonical/desktop-engineering pull request #8
Opened 2023-09-29 08:26 UTC by EduardGomezEscandell

This is useful (needed really) if you need to run actions on a sub-directory of a monorepo.

2023-09-29 08:29 UTC, EduardGomezEscandell commented
Pinging @didrocks for a sanity check.

2023-09-29 08:38 UTC, didrocks requested changes
I think that rather than duplicating working-directory in most of the jobs, we can use a default that is overridable per job, like in https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun. WDYT?

2023-09-29 12:34 UTC, EduardGomezEscandell commented
> it seems this is only for run jobs, so won’t fix all the cases, maybe digging into that direction to see if anything exists?

Yeah, that is the problem. I did digg a bit and I couldn't find any way to change the working dir (otherwise this PR would not be necessary, as the caller could use such a tool).

The best we can do is use the default for run, and otherwise be careful with every other action (pre-prend to paths, see if they have their own working-dir option, etc).

2023-09-29 12:41 UTC, didrocks commented
> The best we can do is use the default for run, and otherwise be careful with every other action (pre-prend to paths, see if they have their own working-dir option, etc).

+1

2023-10-02 07:29 UTC, EduardGomezEscandell commented
Well, it seemse that default values for jobs only work in Workflows, not actions. So it seems like this PR is ready.

2023-10-02 07:35 UTC, didrocks commented
You can have it either on the workflow but also at the job level: https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#setting-default-values-for-a-specific-job. Did you try the job level too in the action?

2023-10-02 07:44 UTC, EduardGomezEscandell commented
Actions don't have jobs, only `runs`. The following yaml is not valid:
```yaml
runs:
  uses: ubuntu-latest
  defaults:
    run:
      working-directory: ${{ inputs.working-directory }}
  steps:
    # ...
```

In general, the schema for actions is much more limited:
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions

2023-10-02 07:46 UTC, didrocks commented
Ack then, let’s go with this! Thanks for digging :)

2023-10-02 08:17 UTC, didrocks approved these changes
Thanks for looking for the simplification! Unfortunate that we couldn't though.

I’ll just update the merge commit title before merging. Thanks!

2023-10-02 08:17 UTC, merged